## get request by user
GET http://127.0.0.1:5000/api/products/
Content-Type: application/json

### CREATED
POST http://127.0.0.1:5000/api/products/
Content-Type: application/json

{
    "name": "producto prueba",
    "price": 200,
    "stock_actual": 100,
    "stock_inicial": 100,
    "category_id": 1

}
###dddddddddddddddddddddddddddddddddddd
PUT http://127.0.0.1:5000/api/products/1
Content-Type: application/json

{
    "name": "producto prueba",
    "price": 200,
    "stock_actual": 200,
    "stock_inicial": 200,
    "category_id": 1,
    "description": "producto prueba",
    "imagen_path": "https://example.com/image.jpg"
}