class Constantes:
# Catalog Codes
    CATALOG_PRODUCT_STATUS = 'T_ESTADO_PRODUCTO'
    CATALOG_CATEGORY_STATUS = 'T_ESTADO_CATEGORIA'
    CATALOG_USER_STATUS = 'T_ESTADO_USUARIO'
    CATALOG_STORAGE_STATUS = 'T_ESTADO_STORAGE'
    CATALOG_INVOICE_STATUS = 'T_ESTADO_SOLICITUD'
    CATALOG_STATUS = 'T_ESTADO'
    # Status Values
    STATUS_ACTIVE = 'ACTIVO'
    STATUS_INACTIVE = 'INACTIVO'
    STATUS_DELETED = 'ELIMINADO'
    STATUS_PENDING = 'PENDIENTE'
    STATUS_SENT_SUNAT = 'ENVIADO A SUNAT'

    
    # --- Constants ---
    CURRENCY_PEN = "PEN"
    UNIT_CODE_NIU = "NIU"
    PRICE_TYPE_CODE_MAIN = "01"
    TAX_NAME_IGV = "IGV"
    TAX_TYPE_CODE_VAT = "VAT"
    CATALOG_07_IGV = "CAT_07_IGV"

    # --- XML Placeholders ---
    PLACEHOLDER_DATOS_EMISOR = "@DatosEmisor"
    PLACEHOLDER_DATA_RAZON_EMISOR = "@DataRazonEmisor"
    PLACEHOLDER_DATOS_CLIENTE = "@DatosCliente"
    PLACEHOLDER_DETALLE_PRODUCTOS = "@detalle_productos"
    PLACEHOLDER_DETALLE_PRODUCTOS_NC_ND = "@detalle_productos_nc_nd"
    PLACEHOLDER_FECHA = "@fecha"
    PLACEHOLDER_HORA = "@hora"
    PLACEHOLDER_SERIE = "@serie"
    PLACEHOLDER_TIPO_MONEDA = "@tipo_moneda"
    PLACEHOLDER_TIPO_DOCUMENTO = "@tipo"
    PLACEHOLDER_MONTO_TOTAL = "@monto_total"
    PLACEHOLDER_MONTO_IGV = "@monto_igv"
    PLACEHOLDER_SUBTOTAL = "@subtotal"
    PLACEHOLDER_OBSERVACION = "@observacion"
    PLACEHOLDER_CODIGO_TABLA = "@codigo_table"
    PLACEHOLDER_CODIGO_MENSAJE_TABLA = "@codigo_mensaje_table"
    PLACEHOLDER_DOCUMENTO_REFERENCIADO = "@document_refenced"
    PLACEHOLDER_TIPO_DOCUMENTO_REFERENCIADO = "@document_type_refenced"
