"""ADD data for invoice

Revision ID: 012c9f264ace
Revises: 9a41b369730f
Create Date: 2025-04-24 01:03:40.664892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012c9f264ace'
down_revision = '9a41b369730f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=False))
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'master_data', ['id_status'], ['id'])
        batch_op.drop_column('type_invoice_id')

    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.alter_column('subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('total')
        batch_op.drop_column('tax')
        batch_op.drop_column('discount')
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_invoice_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('id_status')
        batch_op.drop_column('tax')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
