"""change herencia audi

Revision ID: 0f02c327c2f1
Revises: aecfaa0f9257
Create Date: 2025-04-29 18:12:55.283920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f02c327c2f1'
down_revision = 'aecfaa0f9257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('invoice_detail', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
