"""actualizacion de indices

Revision ID: 0fd5d7918b0a
Revises: 90a08cb421da
Create Date: 2025-07-09 23:59:32.438001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd5d7918b0a'
down_revision = '90a08cb421da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_invoice_serie_num', ['num_invoice', 'serie'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_serie_num', type_='unique')

    # ### end Alembic commands ###
