"""change product

Revision ID: 258832f8ff0f
Revises: 0f02c327c2f1
Create Date: 2025-04-29 18:34:40.301835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258832f8ff0f'
down_revision = '0f02c327c2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=True))
        batch_op.drop_column('eid_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eid_status', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('id_status')

    # ### end Alembic commands ###
