"""mejora en categoria

Revision ID: 34e33540ed58
Revises: 78458fa32bbf
Create Date: 2025-08-07 00:02:14.442750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e33540ed58'
down_revision = '78458fa32bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('category_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('category_description_key', ['description'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
