"""update storage

Revision ID: 4247d3af57d1
Revises: 0464d2f9cd0b
Create Date: 2025-05-12 16:24:00.750938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4247d3af57d1'
down_revision = '0464d2f9cd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=True))
        batch_op.drop_column('eid_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eid_status', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('id_status')

    # ### end Alembic commands ###
