"""update product model relationships

Revision ID: 4dba4ef3a035
Revises: 628a0c5328b9
Create Date: 2025-05-08 01:31:57.961270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dba4ef3a035'
down_revision = '628a0c5328b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=21), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_business', sa.Boolean(), nullable=True),
    sa.Column('commercial_name', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('document_type', sa.String(length=1), nullable=False, comment='Tipo de documento según SUNAT'),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('master_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_value', sa.String(length=50), nullable=False),
    sa.Column('description_value', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('code_table', sa.String(length=50), nullable=False),
    sa.Column('description_table', sa.String(length=255), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_value')
    )
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_path', sa.String(length=500), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('eid_status', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('num_invoice', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['id_status'], ['master_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num_invoice')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('stock_inicial', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('id_status', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_storage',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'storage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_storage')
    op.drop_table('payment')
    op.drop_table('invoice_detail')
    op.drop_table('product')
    op.drop_table('invoice')
    op.drop_table('user')
    op.drop_table('storage')
    op.drop_table('master_data')
    op.drop_table('customer')
    op.drop_table('category')
    # ### end Alembic commands ###
