"""ADD data for customers

Revision ID: 9a41b369730f
Revises: 6065dc71983b
Create Date: 2025-04-24 00:33:45.451540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a41b369730f'
down_revision = '6065dc71983b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('document_number', sa.String(length=21), nullable=False))
        batch_op.add_column(sa.Column('is_business', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('commercial_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('document_type', sa.String(length=1), nullable=False, comment='Tipo de documento según SUNAT'))
        batch_op.create_unique_constraint(None, ['document_number'])
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('document_type')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('province')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('business_name')
        batch_op.drop_column('commercial_name')
        batch_op.drop_column('is_business')
        batch_op.drop_column('document_number')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
