"""agregar nuevo para las ref

Revision ID: a2e956549392
Revises: 9c73813946ef
Create Date: 2025-07-28 02:32:21.748166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e956549392'
down_revision = '9c73813946ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_invoice_id', sa.Integer(), nullable=True))
        batch_op.alter_column('num_invoice',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'invoice', ['related_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('num_invoice',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('related_invoice_id')

    # ### end Alembic commands ###
