"""remove user_type

Revision ID: ab4ff446cd27
Revises: 012c9f264ace
Create Date: 2025-04-24 01:20:08.546245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4ff446cd27'
down_revision = '012c9f264ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_typedocument')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_typedocument',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typedocument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['typedocument_id'], ['master_data.id'], name='user_typedocument_typedocument_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_typedocument_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'typedocument_id', name='user_typedocument_pkey')
    )
    # ### end Alembic commands ###
