"""change herencia audi

Revision ID: aecfaa0f9257
Revises: d9ef2a4fc0f9
Create Date: 2025-04-29 18:09:00.601552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecfaa0f9257'
down_revision = 'd9ef2a4fc0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('modifiedBy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('modifiedAt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('modifiedAt')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('modifiedBy')
        batch_op.drop_column('createdBy')
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
