"""ADD MIDDLE2

Revision ID: b27eb804d345
Revises: f89bae2c8001
Create Date: 2025-04-23 18:55:12.768455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27eb804d345'
down_revision = 'f89bae2c8001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_typedocument',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_typedocument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_typedocument_id'], ['master_data.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'user_typedocument_id')
    )
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data_value', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description_value', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=False))
        batch_op.drop_constraint('master_data_type_document_key', type_='unique')
        batch_op.create_unique_constraint(None, ['data_value'])
        batch_op.drop_column('id_document')
        batch_op.drop_column('status')
        batch_op.drop_column('type_description')
        batch_op.drop_column('type_document')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus_id', sa.Integer(), nullable=True))
        batch_op.drop_column('is_active')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.alter_column('estatus_id',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('document_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('document_number')
        batch_op.drop_column('id_status')

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.alter_column('estatus_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('estatus_id')

    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_document', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_document', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('master_data_type_document_key', ['type_document'])
        batch_op.drop_column('id_status')
        batch_op.drop_column('description_value')
        batch_op.drop_column('data_value')
        batch_op.drop_column('id')

    op.drop_table('user_typedocument')
    # ### end Alembic commands ###
