"""change id_status

Revision ID: d9ef2a4fc0f9
Revises: ab4ff446cd27
Create Date: 2025-04-29 17:21:59.203460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ef2a4fc0f9'
down_revision = 'ab4ff446cd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=True))
        batch_op.drop_column('status_id')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_status', sa.Integer(), nullable=False))
        batch_op.drop_constraint('invoice_status_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'master_data', ['id_status'], ['id'])
        batch_op.drop_column('status_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eid_status', sa.Integer(), nullable=True))
        batch_op.drop_column('estatus_id')

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eid_status', sa.Integer(), nullable=True))
        batch_op.drop_column('estatus_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('eid_status')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('eid_status')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoice_status_id_fkey', 'master_data', ['status_id'], ['id'])
        batch_op.drop_column('id_status')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('id_status')

    # ### end Alembic commands ###
