"""init

Revision ID: f275a7be56b4
Revises: 
Create Date: 2025-06-26 22:42:06.288754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f275a7be56b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=2), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('ultimo_correlativo', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=80), nullable=True),
    sa.Column('createdBy', sa.String(length=80), nullable=True),
    sa.Column('modifiedBy', sa.String(length=80), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_comprobante', 'serie', name='uq_tipo_serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie')
    # ### end Alembic commands ###
